//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalogue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Images = new HashSet<Image>();
            this.ProductsTags = new HashSet<ProductsTag>();
        }
    
        public int ProductsID { get; set; }
        public string Name { get; set; }
        public int CategoryID { get; set; }
        public int ManufacturerID { get; set; }
        public System.DateTime ProductYear { get; set; }
        public string Description { get; set; }
        public int RatingID { get; set; }
        public int TagsID { get; set; }
        public int CommentsID { get; set; }
        public int LikeDislikeID { get; set; }
        public int WishlistID { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
        public virtual Wishlist Wishlist { get; set; }
        public virtual ICollection<ProductsTag> ProductsTags { get; set; }
    }
}
